export const profileCopy = {
  title: 'Complete seu perfil',
  subtitle: 'Esses dados ajudam sua turma a reconhecer você.',
  displayName: 'Como devemos chamar você?',
  avatarUrl: 'URL da foto (opcional)',
  submit: 'Concluir cadastro',
  genericError: 'Não foi possível salvar seu perfil. Tente novamente.',
  editTitle: 'Seu perfil',
  editSubtitle: 'Atualize sua identidade e preferências do aplicativo.',
  save: 'Salvar alterações',
  saved: 'Perfil atualizado com sucesso.',
  account: 'Sua conta',
  email: 'E-mail',
  memberSince: 'No Pacer desde',
  signOut: 'Sair da conta',
  signOutError: 'Não foi possível sair da conta. Tente novamente.',
  loadError: 'Não foi possível carregar seu perfil.',
  retry: 'Tentar novamente',
} as const
